### ISSUE TITLE
How to get current Color according to thumb's position.

### ISSUE THREAD

**Issue by ApexcupDeveloper** [jonhull/GradientSlider#14]
Hi, Thanks for great Library.
I am trying to use it in my project. I have set the minColor and maxColor and it works well.
At that time, how to get current color between minColor and maxColor?
Please let me know.
Thanks

**Comment by BubblyNetDev** [comment]
This would be very helpful for me as well.

**Comment by ApexcupDeveloper** [comment]
I solved it
