### ISSUE TITLE
add endedBlock that is called when sliding ended

### ISSUE THREAD

**Issue by GerdC** [jonhull/GradientSlider#3]
I needed to know when sliding ended (in addition to the continuous values). So I added the following code:

```
var actionBlock:(GradientSlider,CGFloat)->() = {slider,newValue in }
var endedBlock:(GradientSlider,CGFloat)->() = {slider,newValue in }  // new


override func endTrackingWithTouch(touch: UITouch?, withEvent event: UIEvent?) {
    if let pt = touch?.locationInView(self){
        let newValue = valueForLocation(pt)
        setValue(newValue, animated: false)
    }
    actionBlock(self,_value)
    endedBlock(self,_value)  // new
    sendActionsForControlEvents([UIControlEvents.ValueChanged, UIControlEvents.TouchUpInside])
}
```

You might consider adding this to your code under the given license.

Thanks for your code! 

Gerd

**Comment by jonhull** [comment]
Thanks, I can see that being a necessary use case.  Would your problem be solved if I added a boolean to the actionBlock indicating whether it is being triggered based on the touchUp event?

I am considering updating everything for the Swift 3 naming conventions once Swift 3 is released, so if I am going to make a breaking change... that would be the time to do it.

**Comment by pmbfish40** [comment]
Where should i add this code to detect when sliding is ended?

**Comment by jonhull** [comment]
Added in the latest update...
